// Prepare demo data
var odata = [{
    "hc-key": "us-ca-24",
    "district": 0,
    "humans": 500,
    "zombies": 0,
    "value": 1
}, {
    "hc-key": "us-id-01",
    "district": 1,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tn-02",
    "district": 2,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ne-02",
    "district": 3,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-md-06",
    "district": 4,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ma-09",
    "district": 5,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wi-08",
    "district": 6,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wi-03",
    "district": 7,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mi-01",
    "district": 8,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ut-03",
    "district": 9,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-az-01",
    "district": 10,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-me-02",
    "district": 11,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-la-03",
    "district": 12,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-23",
    "district": 13,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nm-02",
    "district": 14,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tn-05",
    "district": 15,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-sd-00",
    "district": 16,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wy-00",
    "district": 17,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-23",
    "district": 18,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-pa-05",
    "district": 19,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-co-03",
    "district": 20,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nm-03",
    "district": 21,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-14",
    "district": 22,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-47",
    "district": 23,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-26",
    "district": 24,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-14",
    "district": 25,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-26",
    "district": 26,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wv-01",
    "district": 27,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-pa-18",
    "district": 28,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ri-02",
    "district": 29,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ct-02",
    "district": 30,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-10",
    "district": 31,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tn-04",
    "district": 32,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mi-02",
    "district": 33,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mi-03",
    "district": 34,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-va-10",
    "district": 35,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mn-02",
    "district": 36,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mn-06",
    "district": 37,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mn-04",
    "district": 38,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-il-01",
    "district": 39,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-il-05",
    "district": 40,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-il-07",
    "district": 41,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-il-02",
    "district": 42,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-33",
    "district": 43,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-36",
    "district": 44,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-31",
    "district": 45,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-48",
    "district": 46,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-46",
    "district": 47,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ar-03",
    "district": 48,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ar-02",
    "district": 49,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-34",
    "district": 50,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-30",
    "district": 51,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-18",
    "district": 52,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-20",
    "district": 53,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-16",
    "district": 54,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-22",
    "district": 55,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-37",
    "district": 56,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-43",
    "district": 57,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-32",
    "district": 58,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-35",
    "district": 59,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-42",
    "district": 60,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-49",
    "district": 61,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-44",
    "district": 62,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-15",
    "district": 63,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-19",
    "district": 64,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-10",
    "district": 65,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ia-04",
    "district": 66,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ia-02",
    "district": 67,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mn-03",
    "district": 68,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mn-05",
    "district": 69,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-52",
    "district": 70,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-25",
    "district": 71,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-29",
    "district": 72,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-07",
    "district": 73,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-06",
    "district": 74,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-39",
    "district": 75,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-al-05",
    "district": 76,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-02",
    "district": 77,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-12",
    "district": 78,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-05",
    "district": 79,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-11",
    "district": 80,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-03",
    "district": 81,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-il-04",
    "district": 82,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-il-16",
    "district": 83,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-in-04",
    "district": 84,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-in-01",
    "district": 85,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wi-01",
    "district": 86,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-il-10",
    "district": 87,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-50",
    "district": 88,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-53",
    "district": 89,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-08",
    "district": 90,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-il-06",
    "district": 91,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-il-03",
    "district": 92,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ga-04",
    "district": 93,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ga-05",
    "district": 94,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ga-13",
    "district": 95,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ga-10",
    "district": 96,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tn-03",
    "district": 97,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-51",
    "district": 98,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-28",
    "district": 99,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ga-07",
    "district": 100,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ga-09",
    "district": 101,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ga-06",
    "district": 102,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ga-14",
    "district": 103,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-la-06",
    "district": 104,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-la-01",
    "district": 105,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ms-04",
    "district": 106,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ar-04",
    "district": 107,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-la-05",
    "district": 108,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ar-01",
    "district": 109,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-in-02",
    "district": 110,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-in-05",
    "district": 111,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-in-09",
    "district": 112,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-in-07",
    "district": 113,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-in-06",
    "district": 114,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-in-03",
    "district": 115,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-il-11",
    "district": 116,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-il-09",
    "district": 117,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-il-18",
    "district": 118,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-il-15",
    "district": 119,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-40",
    "district": 120,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-13",
    "district": 121,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-45",
    "district": 122,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ia-03",
    "district": 123,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ga-11",
    "district": 124,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-04",
    "district": 125,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-09",
    "district": 126,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tn-08",
    "district": 127,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tn-09",
    "district": 128,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-41",
    "district": 129,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-27",
    "district": 130,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-17",
    "district": 131,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ky-01",
    "district": 132,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ky-05",
    "district": 133,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ky-03",
    "district": 134,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ky-02",
    "district": 135,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ky-04",
    "district": 136,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-il-12",
    "district": 137,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-il-08",
    "district": 138,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-or-04",
    "district": 139,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-38",
    "district": 140,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-al-04",
    "district": 141,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ms-01",
    "district": 142,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-22",
    "district": 143,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mo-01",
    "district": 144,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mo-03",
    "district": 145,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mo-08",
    "district": 146,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-al-07",
    "district": 147,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-al-06",
    "district": 148,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-al-01",
    "district": 149,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-al-02",
    "district": 150,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nj-03",
    "district": 151,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nj-05",
    "district": 152,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nj-07",
    "district": 153,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nj-02",
    "district": 154,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nj-09",
    "district": 155,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nj-06",
    "district": 156,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nj-10",
    "district": 157,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nv-02",
    "district": 158,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-id-02",
    "district": 159,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ut-01",
    "district": 160,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ga-12",
    "district": 161,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-sc-03",
    "district": 162,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-sc-01",
    "district": 163,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-sc-07",
    "district": 164,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-sc-06",
    "district": 165,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ga-01",
    "district": 166,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wa-10",
    "district": 167,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wa-03",
    "district": 168,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wa-06",
    "district": 169,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-oh-10",
    "district": 170,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-oh-15",
    "district": 171,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-oh-07",
    "district": 172,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-oh-13",
    "district": 173,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-oh-04",
    "district": 174,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-oh-09",
    "district": 175,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-oh-01",
    "district": 176,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-oh-11",
    "district": 177,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-oh-05",
    "district": 178,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mi-07",
    "district": 179,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mi-08",
    "district": 180,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-oh-08",
    "district": 181,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-oh-12",
    "district": 182,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-va-01",
    "district": 183,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-va-05",
    "district": 184,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-va-04",
    "district": 185,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-va-02",
    "district": 186,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-va-09",
    "district": 187,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mi-06",
    "district": 188,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mi-04",
    "district": 189,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mi-14",
    "district": 190,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mi-13",
    "district": 191,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mi-10",
    "district": 192,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mi-05",
    "district": 193,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mi-11",
    "district": 194,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mi-09",
    "district": 195,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mi-12",
    "district": 196,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-va-08",
    "district": 197,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wa-07",
    "district": 198,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wa-02",
    "district": 199,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wa-01",
    "district": 200,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wa-09",
    "district": 201,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wa-08",
    "district": 202,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nj-11",
    "district": 203,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nj-08",
    "district": 204,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-co-01",
    "district": 205,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-co-04",
    "district": 206,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ok-03",
    "district": 207,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-co-02",
    "district": 208,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-co-07",
    "district": 209,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-co-06",
    "district": 210,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-md-01",
    "district": 211,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-pa-04",
    "district": 212,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-va-11",
    "district": 213,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-md-05",
    "district": 214,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-md-03",
    "district": 215,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-md-07",
    "district": 216,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-md-02",
    "district": 217,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-md-04",
    "district": 218,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-md-08",
    "district": 219,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-dc-98",
    "district": 220,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mo-04",
    "district": 221,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ks-03",
    "district": 222,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mo-07",
    "district": 223,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ks-02",
    "district": 224,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ma-03",
    "district": 225,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ma-05",
    "district": 226,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ma-07",
    "district": 227,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-vt-00",
    "district": 228,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ma-02",
    "district": 229,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ma-04",
    "district": 230,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ma-06",
    "district": 231,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ma-08",
    "district": 232,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wv-03",
    "district": 233,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-oh-06",
    "district": 234,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-il-17",
    "district": 235,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wi-02",
    "district": 236,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wi-04",
    "district": 237,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wi-07",
    "district": 238,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wi-06",
    "district": 239,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nc-01",
    "district": 240,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-sc-04",
    "district": 241,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nc-10",
    "district": 242,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nc-11",
    "district": 243,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-sc-05",
    "district": 244,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nc-08",
    "district": 245,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nc-06",
    "district": 246,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nc-02",
    "district": 247,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nc-12",
    "district": 248,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nh-01",
    "district": 249,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nh-02",
    "district": 250,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ks-04",
    "district": 251,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ok-01",
    "district": 252,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-de-00",
    "district": 253,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-pa-01",
    "district": 254,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-pa-13",
    "district": 255,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nj-01",
    "district": 256,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-pa-07",
    "district": 257,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-pa-02",
    "district": 258,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-pa-03",
    "district": 259,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-pa-10",
    "district": 260,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-22",
    "district": 261,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-pa-06",
    "district": 262,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-pa-16",
    "district": 263,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-pa-08",
    "district": 264,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-pa-09",
    "district": 265,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-pa-15",
    "district": 266,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-pa-12",
    "district": 267,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nj-12",
    "district": 268,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nj-04",
    "district": 269,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-08",
    "district": 270,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-17",
    "district": 271,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-09",
    "district": 272,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-07",
    "district": 273,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-27",
    "district": 274,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-14",
    "district": 275,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-13",
    "district": 276,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-24",
    "district": 277,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-16",
    "district": 278,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-11",
    "district": 279,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-15",
    "district": 280,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-23",
    "district": 281,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-06",
    "district": 282,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-12",
    "district": 283,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-18",
    "district": 284,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ga-08",
    "district": 285,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-02",
    "district": 286,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-20",
    "district": 287,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-25",
    "district": 288,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-19",
    "district": 289,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-03",
    "district": 290,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-10",
    "district": 291,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-az-03",
    "district": 292,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-az-05",
    "district": 293,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-az-07",
    "district": 294,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-az-06",
    "district": 295,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-az-09",
    "district": 296,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ut-02",
    "district": 297,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-az-04",
    "district": 298,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-az-08",
    "district": 299,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-06",
    "district": 300,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-17",
    "district": 301,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-16",
    "district": 302,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-27",
    "district": 303,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-15",
    "district": 304,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-24",
    "district": 305,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-30",
    "district": 306,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-02",
    "district": 307,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-29",
    "district": 308,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-32",
    "district": 309,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-20",
    "district": 310,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-21",
    "district": 311,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-03",
    "district": 312,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-31",
    "district": 313,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-10",
    "district": 314,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ok-04",
    "district": 315,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-04",
    "district": 316,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ok-02",
    "district": 317,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-la-04",
    "district": 318,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-25",
    "district": 319,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-35",
    "district": 320,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-28",
    "district": 321,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-11",
    "district": 322,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-13",
    "district": 323,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-26",
    "district": 324,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-07",
    "district": 325,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-22",
    "district": 326,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-36",
    "district": 327,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-09",
    "district": 328,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-18",
    "district": 329,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ri-01",
    "district": 330,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ma-01",
    "district": 331,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ct-01",
    "district": 332,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ct-05",
    "district": 333,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ct-03",
    "district": 334,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ct-04",
    "district": 335,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-03",
    "district": 336,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mt-00",
    "district": 337,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-01",
    "district": 338,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-27",
    "district": 339,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-25",
    "district": 340,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-14",
    "district": 341,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-06",
    "district": 342,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-07",
    "district": 343,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-05",
    "district": 344,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-24",
    "district": 345,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-16",
    "district": 346,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-17",
    "district": 347,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-11",
    "district": 348,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-15",
    "district": 349,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-08",
    "district": 350,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-12",
    "district": 351,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-18",
    "district": 352,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-02",
    "district": 353,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-04",
    "district": 354,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-13",
    "district": 355,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-09",
    "district": 356,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-21",
    "district": 357,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-19",
    "district": 358,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mn-07",
    "district": 359,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ne-01",
    "district": 360,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ne-03",
    "district": 361,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-il-14",
    "district": 362,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-or-01",
    "district": 363,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-or-03",
    "district": 364,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tn-07",
    "district": 365,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nc-05",
    "district": 366,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tn-01",
    "district": 367,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-il-13",
    "district": 368,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ga-03",
    "district": 369,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-01",
    "district": 370,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tn-06",
    "district": 371,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ga-02",
    "district": 372,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-al-03",
    "district": 373,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mo-05",
    "district": 374,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mo-06",
    "district": 375,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nv-04",
    "district": 376,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nv-03",
    "district": 377,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nv-01",
    "district": 378,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-sc-02",
    "district": 379,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-oh-16",
    "district": 380,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-oh-14",
    "district": 381,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-oh-03",
    "district": 382,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-va-03",
    "district": 383,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-va-07",
    "district": 384,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-va-06",
    "district": 385,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wa-04",
    "district": 386,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wi-05",
    "district": 387,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nc-07",
    "district": 388,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nc-04",
    "district": 389,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nc-13",
    "district": 390,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nc-09",
    "district": 391,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ok-05",
    "district": 392,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-pa-17",
    "district": 393,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-pa-14",
    "district": 394,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-pa-11",
    "district": 395,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-19",
    "district": 396,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-08",
    "district": 397,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-01",
    "district": 398,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-33",
    "district": 399,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-12",
    "district": 400,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-26",
    "district": 401,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nc-03",
    "district": 402,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mn-08",
    "district": 403,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-me-01",
    "district": 404,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-34",
    "district": 405,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mn-01",
    "district": 406,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-23",
    "district": 407,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-oh-02",
    "district": 408,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-21",
    "district": 409,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-04",
    "district": 410,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-05",
    "district": 411,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-az-02",
    "district": 412,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-tx-05",
    "district": 413,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-in-08",
    "district": 414,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-la-02",
    "district": 415,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-fl-01",
    "district": 416,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ms-03",
    "district": 417,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wv-02",
    "district": 418,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-or-05",
    "district": 419,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nd-00",
    "district": 420,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ia-01",
    "district": 421,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-wa-05",
    "district": 422,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ks-01",
    "district": 423,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ms-02",
    "district": 424,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-or-02",
    "district": 425,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-mo-02",
    "district": 426,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-co-05",
    "district": 427,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ny-20",
    "district": 428,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-nm-01",
    "district": 429,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ca-21",
    "district": 430,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ky-06",
    "district": 431,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ut-04",
    "district": 432,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "district": 433,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-hi-02",
    "district": 434,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-hi-01",
    "district": 435,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "hc-key": "us-ak-00",
    "district": 436,
    "humans": 500,
    "zombies": 0,
    "value": 0
}, {
    "district": 437
}];
